/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminNavbar: typeof import('./src/components/navbar/admin-navbar.vue')['default']
    CommonAvatar: typeof import('./src/components/common/common-avatar.vue')['default']
    CommonButton: typeof import('./src/components/common/common-button.vue')['default']
    CommonHeader: typeof import('./src/components/common/common-header.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    InputField: typeof import('./src/components/reusable/input-field.vue')['default']
    LoginComponent: typeof import('./src/components/LoginComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserHome: typeof import('./src/components/user/user-home.vue')['default']
    UserNavbar: typeof import('./src/components/navbar/user-navbar.vue')['default']
  }
}
