/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminNavbar: typeof import('./src/components/navbar/admin-navbar.vue')['default']
    CommonAvatar: typeof import('./src/components/common/common-avatar.vue')['default']
    CommonButton: typeof import('./src/components/common/common-button.vue')['default']
    CommonHeader: typeof import('./src/components/common/common-header.vue')['default']
    CustomeWidget: typeof import('./src/components/reusable/custome-widget.vue')['default']
    CustomWidget: typeof import('./src/components/reusable/custom-widget.vue')['default']
    'Dialog.form': typeof import('./src/components/reusable/dialog.form.vue')['default']
    DialogForm: typeof import('./src/components/reusable/dialog-form.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    InputField: typeof import('./src/components/reusable/input-field.vue')['default']
    LoginComponent: typeof import('./src/components/LoginComponent.vue')['default']
    PaginationPage: typeof import('./src/components/reusable/pagination-page.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatsWidget: typeof import('./src/components/reusable/stats-widget.vue')['default']
    TextArea: typeof import('./src/components/reusable/text-area.vue')['default']
    UserHome: typeof import('./src/components/user/user-home.vue')['default']
    UserNavbar: typeof import('./src/components/navbar/user-navbar.vue')['default']
  }
}
